framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.adapter.apcu
            doctrine.system_cache_pool:
                adapter: cache.adapter.apcu
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'
