version: '3'

services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
    ports:
      - "5432:5432"

  mailer:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"

  store:
    image: eqalpha/keydb:alpine_x86_64_v6.3.2
    ports:
      - "6379:6379"
